-
  name: Configure user to control Kubernetes Cluster
  hosts: master
  tasks:
    -
      name: Create a kube-operator user
      user:
        name: kube-operator
        comment: Kube Operator
        shell: /bin/bash
        group: wheel
    -
      name: Create a kube directory
      file:
        path: /home/kube-operator/.kube
        state: directory
        mode: '0755'
    -
      name: Configure environment to kube-operator
      lineinfile:
        path: /home/kube-operator/.bashrc
        line: export KUBECONFIG=$HOME/.kube/config
    -
      name: Copy kubernetes config file
      command:
        cmd: cp /etc/kubernetes/admin.conf /home/kube-operator/.kube/config
        creates: /home/kube-operator/.kube/config
    -
      name: Set permissions
      file:
        path: /home/kube-operator/.kube/config
        owner: kube-operator
        group: wheel
        mode: 0644
