---
# This playbook installs OLCNE (single master)
-
  name: Apply common configuration to all nodes
  hosts: all
  roles:
    - common

-
  name: Apply common configuration to kubernetes nodes
  hosts: kubernetes
  roles:
    - k8s_node

-
  name: Configure master kubernetes nodes
  hosts: masters
  roles:
    - master

-
  name: Configure workers kubernetes nodes
  hosts: workers
  roles:
    - worker

-
  name: Configure and deploy API Server
  hosts: api-server
  roles:
    - api-server

-
  name: Configure and start OLCNE agent on Kubernetes nodes
  hosts: kubernetes
  tasks:
    -
      name: Start API agent
      command:
        cmd: /etc/olcne/bootstrap-olcne.sh --secret-manager-type file --olcne-node-cert-path /etc/olcne/configs/certificates/production/node.cert --olcne-ca-path /etc/olcne/configs/certificates/production/ca.cert --olcne-node-key-path /etc/olcne/configs/certificates/production/node.key --olcne-component agent
...
