---
# Configure an environment 
- 
  name: Creating an environment
  command:
    cmd: olcnectl --api-server 127.0.0.1:8091 environment create --environment-name {{ env_name }} --update-config --secret-manager-type file --olcne-node-cert-path /etc/olcne/configs/certificates/production/node.cert --olcne-ca-path /etc/olcne/configs/certificates/production/ca.cert --olcne-node-key-path /etc/olcne/configs/certificates/production/node.key
  when: config_env == True

# Configure kubernetes to the environment
-
  name: Adding kubernetes to the environment
  command:
    cmd: olcnectl --api-server 127.0.0.1:8091 module create --environment-name {{ env_name }} --module kubernetes --name {{ cluster }} --container-registry container-registry.oracle.com/olcne --apiserver-advertise-address {{ master_ip_addr }} --master-nodes {{ master_node }} --worker-nodes {{ worker_nodes }} 
  when: config_env == True

# Deploy kubernetes
- 
  name: Deploying the kubernetes module
  command:
    cmd: olcnectl --api-server 127.0.0.1:8091 module install --environment-name {{ env_name }} --name {{ cluster }}
  when: config_env == True

# Configure Helm 3 to the environment
-
  name: Adding helm module to the environment
  command:
    cmd: olcnectl --api-server 127.0.0.1:8091 module create --environment-name {{ env_name }} --module helm --name {{ helm_module }} --helm-kubernetes-module {{ cluster }}
  when: use_helm == True 

# Deploy helm
-
  name: Deploying the helm module
  command:
    cmd: olcnectl --api-server 127.0.0.1:8091 module install --environment-name {{ env_name }} --name {{ helm_module }}
  when: use_helm == True 

# Configure Istio to the environment
-
  name: Adding istio module to the environment
  command:
    cmd: olcnectl --api-server 127.0.0.1:8091 module create --environment-name {{ env_name }} --module istio --name {{ istio_module }} --istio-helm-module {{ helm_module }}
  when: 
    - use_helm == True 
    - use_istio == True

# Deploy helm
-
  name: Deploying the istio module
  command:
    cmd: olcnectl --api-server 127.0.0.1:8091 module install --environment-name {{ env_name }} --name {{ istio_module }}
  when: 
    - use_helm == True 
    - use_istio == True