---
- 
  name: Creating a kube-operator user
  user:
    name: kube-operator
    comment: Kube Operator
    shell: /bin/bash
    group: wheel
  when: add_new == True
 
-
  name: Creating a kube directory
  file:
    path: /home/kube-operator/.kube
    state: directory
    mode: '0755'
  when: add_new == True

-
  name: Configuring environment to kube-operator
  lineinfile:
    path: /home/kube-operator/.bashrc
    line: export KUBECONFIG=$HOME/.kube/config
  when: add_new == True

-
  name: Copying kubernetes config file
  command:
    cmd: cp /etc/kubernetes/admin.conf /home/kube-operator/.kube/config
    creates: /home/kube-operator/.kube/config
  when: add_new == True

-
  name: Setting permissions
  file:
    path: /home/kube-operator/.kube/config
    owner: kube-operator
    group: wheel
    mode: 0600
  when: config_env == True
