---
- 
  name: Creating a kube-operator user
  user:
    name: kube-operator
    comment: Kube Operator
    shell: /bin/bash
    group: wheel
  when: add_new == False
 
-
  name: Creating a kube directory
  file:
    path: /home/kube-operator/.kube
    state: directory
    mode: '0755'
  when: add_new == False

-
  name: Configuring environment to kube-operator
  lineinfile:
    path: /home/kube-operator/.bashrc
    line: export KUBECONFIG=$HOME/.kube/config
  when: add_new == False

-
  name: Copying kubernetes config file
  command:
    cmd: cp /etc/kubernetes/admin.conf /home/kube-operator/.kube/config
    creates: /home/kube-operator/.kube/config
  when: add_new == False

-
  name: Setting permissions
  file:
    path: /home/kube-operator/.kube/config
    owner: kube-operator
    group: wheel
    mode: 0600
  when: add_new == False

# Installing Velero for Backups

-
  name: Download Velero
  get_url: url=https://github.com/vmware-tanzu/velero/releases/download/v{{ velero_version }}/velero-v{{ velero_version }}-linux-amd64.tar.gz dest=/root/
#  when: add_new == False
- 
  name: Installing Velero
  command:
    cmd: tar zxvf velero-v{{ velero_version }}-linux-amd64.tar.gz && cp /root/velero-v{{ velero_version }}-linux-amd64/velero /usr/bin/velero
    creates: /usr/bin/velero
#  when: add_new == False
-
  name: Creating OCI Auth File
  blockinfile:
    path: /home/kube-operator/credential-velero
    block: |
      [default]
      aws_access_key_id={{ oci_access_key }}
      aws_secret_access_key={{ oci_secret_access_key }}
    create: yes
  become: yes
  become_user: kube-operator
#  when: add_new == False
-
  name: Deploying Velero on Kubernetes
  command:
    cmd: velero install --provider aws --plugins velero/velero-plugin-for-aws:v1.1.0 --bucket velero --prefix {{ oci_tenancy }} --use-restic --use-volume-snapshots=false --secret-file /home/kube-operator/credentials-velero --backup-location-config region={{ oci_region }},s3ForcePathStyle="true",s3Url=https://{{ oci_bucket_namespace }}.compat.objectstorage.{{ oci_region }}.oraclecloud.com
  become: yes
  become_user: kube-operator
#  when: add_new == False

