---
-
  name: Configuring repository to NFS on Helm
  command: helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
  become: yes
  become_user: kube-operator
  when: use_nfs == True

- 
  name: Adding NFS Storage Class to Kubernetes
  command: helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner --set nfs.server={{ nfs_server }} --set nfs.path={{ nfs_path }}
  become: yes
  become_user: kube-operator
  when: use_nfs == True

- 
  name: Adding Cert-Manager to Kubernetes
  command: kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.5.3/cert-manager.yaml
  become: yes
  become_user: kube-operator
  when: use_certmanager == True
