---
# tasks file for olcne

# Apply firewall rules for Workers
-
  firewalld:
    port: '{{ item }}'
    permanent: True
    state: enabled
  loop:
    - 8090/tcp
    - 10250/tcp
    - 10255/tcp
    - 8472/udp

# Aplying masquerade firewall rules
#-
#  name: Aplying masquerade firewall rules
#  command:
#    cmd: firewall-cmd --remove-masquerade --permanent

# Aplying CNI interface to firewall rules
-
  name: Aplying CNI interface to firewall rules
  command:
    cmd: firewall-cmd --zone=trusted --add-interface=cni0 --permanent

# Reload firewall rules
-
  name: Reloading firewalld
  command:
    cmd: firewall-cmd --reload

-
  name: Installing NFS Client
  dnf:
    name:
      - nfs-utils
      - nfs4-acl-tools
    state: present
 when: use_nfs == True
...
