---
# tasks file for olcne

# Configure SELinux
-
  name: Disable SELinux
  selinux:
    state: disabled

# Configure Proxy for environment
-
  name: Configure Proxy for DNF
  lineinfile:
    path: /etc/dnf/dnf.conf
    line: "proxy={{ proxy_host }}"
  when: use_proxy == True
-
  name: Configure Proxy for environment
  blockinfile:
    path: /etc/profile.d/sh.local
    block: |
      export all_proxy="{{ proxy_host }}"
      export http_proxy="{{ proxy_host }}"
      export https_proxy="{{ proxy_host }}"
      export no_proxy="{{ no_proxy }}"
    create: yes
  when: use_proxy == True

# Configure general environment
#-
#  name: Update all hosts
#  dnf:
#    name: '*'
#    state: latest
-
  name: Install chrony
  dnf:
    name: chrony
    state: present
-
  name: Start chrony Service
  service:
    name: chronyd
    state: started
    enabled: yes

# Configure DNF repositories and installing packages
-
  name: Installing OLCNE
  dnf:
    name: oracle-olcne-release-el8
    state: present
-
  name: Enabling repositories
  command:
    cmd: dnf config-manager --enable ol8_olcne13 ol8_addons ol8_baseos_latest ol8_UEKR6
...
